# @section nginx_ingress_controller begin
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
  annotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.2
      helm:
        valueFiles:
          - $values/helm/nginx-ingress-controller/values.yaml
    # @param argocd.git_repo_url
    - repoURL: git@github.com:myorg/my-argocd-repo.git
      # @param argocd.git_target_revision
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# @section nginx_ingress_controller end